name: terraform-compliance

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ----- install binaries -----
      - name: Install Terraform & Terragrunt
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false   # terragrunt dislikes the wrapper

      - name: Install terragrunt
        run: |
          TG_VERSION=$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | jq -r .tag_name)
          wget -q https://github.com/gruntwork-io/terragrunt/releases/download/${TG_VERSION}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64 && sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Install terraform-compliance
        run: pip install terraform-compliance

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # ----- create the plan -----
      - name: Terragrunt plan (network stack)
        working-directory: terragrunt/live/envs/core-services/network
        run: |
          terragrunt init -input=false
          terragrunt plan -out ../../../../network.plan -input=false -lock=false

      # ----- run compliance tests -----
      - name: terraform-compliance
        run: terraform-compliance -p terragrunt/network.plan -f tests 